import WeekCard from "./WeekCard";

export default function Roadmap({ roadmap, setRoadmap }) {

  const toggleTask = (weekIndex, taskIndex) => {
    setRoadmap((prev) => {
      const updatedWeeks = prev.weeks.map((week, wIdx) => {
        if (wIdx !== weekIndex) return week;

        return {
          ...week,
          tasks: week.tasks.map((task, tIdx) => {
            if (tIdx !== taskIndex) return task;

            if (typeof task === "string") {
              return { text: task, done: true };
            }

            return {
              ...task,
              done: !task.done,
            };
          }),
        };
      });

      return {
        ...prev,
        weeks: updatedWeeks,
      };
    });
  };

  return (
    <div className="roadmap" style={{ marginBottom: 'var(--space-xl)' }}>
      <div className="roadmap-header section-glass" style={{ marginBottom: 'var(--space-xl)', padding: 'var(--space-lg) var(--space-xl)' }}>
        <div>
          <h2 className="text-gradient" style={{ fontSize: '1.75rem', marginBottom: 'var(--space-xs)' }}>your custom roadmap</h2>
          <p style={{ color: 'var(--color-primary-light)', fontSize: '0.85rem', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
            <span>📅</span> {roadmap.weeks?.length} week
            {roadmap.weeks?.length !== 1 ? "s" : ""} intensive
          </p>
        </div>
        <div style={{ textAlign: 'right' }}>
           <span style={{ fontSize: '0.75rem', color: 'var(--color-text-dim)' }}>generated by goalforge ai</span>
        </div>
      </div>

      <div className="weeks-container" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-xl)' }}>
        {roadmap.weeks.map((week, index) => (
          <WeekCard
            key={index}
            week={week}
            index={index}
            toggleTask={toggleTask}
          />
        ))}
      </div>
    </div>
  );
}